[tool.poetry]
authors = ["Saito Tsutomu <tsutomu7@hotmail.co.jp>"]
classifiers = [
  "Development Status :: 1 - Planning",
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python",
  "Topic :: Software Development",
  "Topic :: Scientific/Engineering",
]
description = "`mip-tool` is a package for Python-MIP."
homepage = "https://github.com/SaitoTsutomu/mip-tool"
license = "Apache-2.0"
name = "mip-tool"
readme = "README.md"
version = "0.2.7"

[tool.poetry.scripts]
mip_tool = "mip_tool.view:main"

[tool.poetry.dependencies]
mip = {version = "^1.15", python = "<3.12"}
pandas = "^1.5"
python = "^3.11"

[tool.poetry.group.dev.dependencies]
black = "^23.1"
flake8 = "^6.0"
isort = "^5.12"
jupyterlab = "^3.6"
mypy = "^1.1"
pytest = "^7.2"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]
