[tool.poetry]
authors = ["Saito Tsutomu <tsutomu7@hotmail.co.jp>"]
classifiers = [
  "Development Status :: 1 - Planning",
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python",
  "Topic :: Software Development",
  "Topic :: Scientific/Engineering",
]
description = "`mip-tool` is a package for Python-MIP."
homepage = "https://github.com/SaitoTsutomu/mip-tool"
license = "Apache-2.0"
name = "mip-tool"
readme = "README.md"
version = "0.2.4"

[tool.poetry.dependencies]
mip = "^1.14"
more-itertools = "^9.0"
pandas = "^1.5"
python = "^3.10"

[tool.poetry.dev-dependencies]
black = "^22.12"
flake8 = "^6.0"
isort = "^5.11"
jupyterlab = "^3.5"
mypy = "^0.991"
pytest = "^7.2"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
