[tool.poetry]
authors = ["Saito Tsutomu <tsutomu7@hotmail.co.jp>"]
classifiers = [
  "Development Status :: 1 - Planning",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python",
  "Topic :: Software Development",
  "Topic :: Scientific/Engineering",
]
description = "`mip-tool` is a package for Python-MIP."
homepage = "https://github.com/SaitoTsutomu/mip-tool"
license = "MIT"
name = "mip-tool"
readme = "README.md"
version = "0.1.2"

[tool.poetry.dependencies]
mip = "^1.13.0"
more-itertools = "^8.10.0"
numpy = "^1.21.1"
pandas = "^1.3.3"
python = "^3.9"

[tool.poetry.dev-dependencies]
black = "^21.9b0"
flake8 = "^4.0.1"
isort = "^5.9.3"
mypy = "^0.910"
pytest = "^5.2"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
